import React from "react";
import "./App.css";

function Pagination({ contacts = [], itemsPerPage = 1, currentPage = 1, onPageChange = () => {} }) {
  // Calculate the index for the current page, calculate the total number of 
  // pages, and calculate the current # of contacts.
  const totalPages = Math.max(1, Math.ceil(contacts.length / itemsPerPage));
  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = contacts.slice(indexOfFirstItem, indexOfLastItem);

  const goToPage = (pageNumber) => {
    if (pageNumber < 1 || pageNumber > totalPages) return;
    onPageChange(pageNumber);
  };

  const goToPrevious = () => goToPage(currentPage - 1);
  const goToNext = () => goToPage(currentPage + 1);

  return (
    // Displays the actual contacts according to the number of contacts
    // Generated by the search. If no contacts can be generated than a 
    // message is returned saying so.
    <div className="contacts-container">
      {currentItems.length > 0 ? (
        currentItems.map((contact) => (
          <div key={contact.id}>
            <div className={`contact ${contact.contactName} ${contact.contactType}`}>
              <img className="fruit-top" src={contact.fruit} alt="" />
              <img className="contact-photo" src={contact.photo} alt={`${contact.name}`} />
              <p><span className="underlined-text">Name</span>: {contact.name}</p>
              <p><span className="underlined-text">Phone</span>: {contact.phone}</p>
              <p><span className="underlined-text">Email</span>: {contact.email}</p>
              <img className="fruit-bottom" src={contact.fruit} alt="" />
            </div>
          </div>
        ))
      ) : (
        <p>No contacts match your search.</p>
      )}

      <div className="page-nav">
        {/* This is the previous Button, which takes the user one contact back */}
        <button className="nav-button" onClick={goToPrevious} disabled={currentPage === 1}>
          Previous
        </button>

        {/* These are page number buttons that let the user skip to specific contacts*/}
        {Array.from({ length: totalPages }, (_, index) => {
          const page = index + 1;
          return (
            <button
              key={page}
              onClick={() => goToPage(page)}
              className="nav-button"
              style={{ margin: "5px", backgroundColor: page === currentPage ? "#007bff" : undefined, color: page === currentPage ? "#fff" : undefined }}
              disabled={page === currentPage}
            >
              {page}
            </button>
          );
        })}

        {/* This is the next Button, which takes the user one contact forward */}
        <button className="nav-button" onClick={goToNext} disabled={currentPage === totalPages}>
          Next
        </button>
      </div>
    </div>
  );
}

export default Pagination;
